// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Project struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	IsGen     sql.NullInt32  `json:"is_gen"`
	CreatedAt time.Time      `json:"created_at"`
}

type Tb struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	ProjectID sql.NullInt32  `json:"project_id"`
	Describe  sql.NullString `json:"describe"`
	CreatedAt time.Time      `json:"created_at"`
}

type TbField struct {
	ID         int32          `json:"id"`
	FieldName  sql.NullString `json:"field_name"`
	LaravelMap sql.NullString `json:"laravel_map"`
	TableID    sql.NullInt32  `json:"table_id"`
}
