// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateProjects(ctx context.Context, arg CreateProjectsParams) (Project, error)
	CreateTb(ctx context.Context, arg CreateTbParams) (Tb, error)
	CreateTbField(ctx context.Context, arg CreateTbFieldParams) (TbField, error)
	DeleteProject(ctx context.Context, id int32) error
	DeleteTb(ctx context.Context, id int32) error
	DeleteTbByPID(ctx context.Context, projectID sql.NullInt32) error
	DeleteTbFieldByTableID(ctx context.Context, tableID sql.NullInt32) error
	GetProject(ctx context.Context, id int32) (Project, error)
	GetProjectByName(ctx context.Context, name sql.NullString) (Project, error)
	GetTFByfID(ctx context.Context, tableID sql.NullInt32) ([]TbField, error)
	GetTFBytID(ctx context.Context, tableID sql.NullInt32) ([]TbField, error)
	GetTb(ctx context.Context, id int32) (Tb, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListTb(ctx context.Context, arg ListTbParams) ([]Tb, error)
	ListTbField(ctx context.Context, arg ListTbFieldParams) ([]TbField, error)
	TruncateProject(ctx context.Context) error
	TruncateTB(ctx context.Context) error
	TruncateTbField(ctx context.Context) error
	UpdateTb(ctx context.Context, arg UpdateTbParams) (Tb, error)
	WhereTbByPID(ctx context.Context, arg WhereTbByPIDParams) ([]Tb, error)
}

var _ Querier = (*Queries)(nil)
